import { Prisma, PrismaClient } from '@prisma/client';
import { prismaHains } from './prisma-hains';

let prismaDb: PrismaClient<Prisma.PrismaClientOptions, 'query'>;

function getDataByHash(data: any, key = 'id') {
  return data.reduce((hash: any, value: any) => {
    hash[value[key]] = value;
    return hash;
  }, {});
}

function convertStringToSnakeCase(str:string){
  return str
    .toLowerCase()
    .replace(/[-\s]+/g, '_');
}

function getHashWithConvertedPlanname(prefix: string, dataArr: any[]) {
  return dataArr.reduce((hashObj:any, dataItem: any) => {
    const converted_planname = convertStringToSnakeCase(dataItem.planname);
    dataItem['converted_planname'] = `${prefix}-${converted_planname}`;
    hashObj[dataItem.id] = dataItem
    return hashObj;
  }, {});
}

function processData<T>(hashKey: keyof T = 'id' as keyof T, dataArr: T[], cbs?: ((data: T) => T)[]) {
  return dataArr.reduce((hashObj: Record<string | number, T>, dataItem: T) => {
    let processedItem = dataItem;

    if (Array.isArray(cbs)) {
      processedItem = cbs.reduce((item, cb) => cb(item), dataItem);
    }

    const key = processedItem[hashKey];
    if (key !== undefined && (typeof key === 'string' || typeof key === 'number')) {
      hashObj[key] = processedItem;
    }

    return hashObj;
  }, {});
}

function convertBereichPlanname(data: any) {
  const converted_planname = convertStringToSnakeCase(data.planname);
  data['converted_planname'] = `b-${converted_planname}`;
  return data;
}

function convertDienstPlanname(data: any) {
  const converted_planname = convertStringToSnakeCase(data.planname);
  data['converted_planname'] = `d-${converted_planname}`;
  return data;
}

type PrismaModels = Extract<Exclude<keyof PrismaClient, `$${string}`>, string>;

type FindManyArgsTypes = {
  [K in PrismaModels]: K extends keyof PrismaClient
    ? Parameters<PrismaClient[K]['findMany']>[0]
    : never;
};

async function getApiDataByKey<K extends PrismaModels>(
  key: K,
  args: FindManyArgsTypes[K] = {},
  shouldHash = true
) {
  const data = await (prismaDb[key] as any).findMany(args);
  return  shouldHash ? getDataByHash(data) : data
}


async function getAllApiData() {
  prismaDb = prismaHains();
  const res: any = {}

// bereiche -> done
// arbeitszeitverteilungen -> done?
// dienstkategorien -> done but the key is not thema_ids but dienstkategoriethemas
// freigaben
// kontingente -> done but the key is not kontingent_po_dienst but kontingent_po_diensts
// monatsplanung_settings
// mitarbeiters ->
  // accountInfo arr statt obj,
  // freigabetypen_ids, vertragphasen_ids nicht implementiert
  // keys umbennen: account_infos, dienstfreigabes, dienstratings, vertrags
// teams
  // keys:umbenennen: po_diensts, funktions, kontingents
// po_dienste
  // kesy umbenennen: dienstbedarves, dienstratings
// vertraege
// vertragsvarianten
// vertragsphasen
// zeitraumkategorien
//

  const bereicheArr = await getApiDataByKey('bereiches' , {}, false);
  const poDiensteArr = await getApiDataByKey('po_diensts', {
    include: {
      dienstbedarves: {
        select: {
          id: true
        }
      },
      dienstratings:{
        select: {
          id: true
        }
      }
    }
  }, false);

  const bereiche = processData('id', bereicheArr, [convertBereichPlanname])
  const poDienste = processData('id', poDiensteArr, [convertDienstPlanname])

  res['MAX_RATING'] = 5;
  res['MAX_WOCHENENDEN'] = 2;
  res['arbeitsplaetze'] = await getApiDataByKey('arbeitsplatzs');
  res['arbeitszeit_absprachen'] = await getApiDataByKey('arbeitszeit_absprachens');
  res['arbeitszeittypen'] = await getApiDataByKey('arbeitszeittyps');
  res['arbeitszeitverteilungen'] = await getApiDataByKey('arbeitszeitverteilungs');
  res['bereiche'] = bereiche
  res['dienstgruppen'] = await getApiDataByKey('dienstgruppes');
  res['dienstkategorien'] = await getApiDataByKey('dienstkategories', {
    include: {
      dienstkategoriethemas: {
        select: {
          thema_id: true
        }
      }
    }
  });
  res['dienstplanpfade'] = await getApiDataByKey('dienstplan_paths');
  res['dienstverteilungstypen'] = await getApiDataByKey('dienstverteilungstyps');
  res['einteilungskontexte'] = await getApiDataByKey('einteilungskontexts');
  res['einteilungsstatuse'] = await getApiDataByKey('einteilungsstatuses');
  res['freigabestatuse'] = await getApiDataByKey('freigabestatuses');
  res['freigabetypen'] = await getApiDataByKey('freigabetyps');
  res['funktionen'] = await getApiDataByKey('funktions');
  res['kontingente'] = await getApiDataByKey('kontingents', {
    include: {
      kontingent_po_diensts: true
    }
  });
  res['kostenstellen'] = await getApiDataByKey('kostenstelles');
  res['mitarbeiters'] = await getApiDataByKey('mitarbeiters', {
    include: {
      account_infos: true,
      dienstfreigabes : {
        select: {
          id: true
        }
      },
      dienstratings: {
        select: {
          id: true
        }
      },
      vertrags:{
        select: {
          id: true
        }
      }
    }
  });
  res['nicht_einteilen_absprachen'] = await getApiDataByKey('nicht_einteilen_absprachens');
  res['po_dienste'] = poDienste
  res['standorte'] = await getApiDataByKey('standorts');
  res['teams'] = await getApiDataByKey('teams', {
    include: {
      po_diensts: {
        select: {
          id: true
        }
      },
      team_funktions: {
        select:{
          funktion_id: true
        }
      },
      kontingents: {
        select: {
          id: true
        }
      },
      team_kw_krankpuffers: true
    }
  });
  res['themen'] = await getApiDataByKey('themas');
  res['vertraege'] = await getApiDataByKey('vertrags');
  res['vertragsphasen'] = await getApiDataByKey('vertrags_phases');
  res['vertragsvarianten'] = await getApiDataByKey('vertrags_variantes');
  res['zeitraumkategorien'] = await getApiDataByKey('zeitraumkategories');
  res['freigaben'] = await getApiDataByKey('dienstfreigabes');

  return res


  // return {
  //   MAX_RATING: 5,
  //   MAX_WOCHENENDEN: 2,
  //   arbeitsplaetze: result.arbeitsplatzs,
  //   arbeitszeit_absprachen: result.arbeitszeit_absprachens,
  //   arbeitszeittypen: result.arbeitszeittyps,
  //   arbeitszeitverteilungen: result.arbeitszeitverteilungs,
  //   bereiche: result.bereiches,
  //   dienstgruppen: result.dienstgruppes,
  //   dienstkategorien: result.dienstkategories,
  //   dienstplanpfade: result.dienstplan_paths,
  //   dienstverteilungstypen: result.dienstverteilungstyps,
  //   einteilungskontexte: result.einteilungskontexts,
  //   einteilungsstatuse: result.einteilungsstatuses,
  //   freigabestatuse: result.freigabestatuses,
  //   freigabetypen: result.freigabetyps,
  //   funktionen: result.funktions,
  //   kontingente: result.kontingents,
  //   kostenstellen: result.kostenstelles,
  //   mitarbeiters: result.mitarbeiters,
  //   nicht_einteilen_absprachen: result.nicht_einteilen_absprachens,
  //   po_dienste: result.po_diensts,
  //   standorte: result.standorts,
  //   teams: result.teams,
  //   themen: result.themas,
  //   vertraege: result.vertrags,
  //   vertragsphasen: result.vertrags_phases,
  //   vertragsvarianten: result.vertrags_variantes,
  //   zeitraumkategorien: result.zeitraumkategories,
  //   freigaben: result.dienstfreigabes,
  //   monatsplanung_settings: {
  //     vorlagen: [
  //       {
  //         id: 6,
  //         mitarbeiter_id: 12,
  //         name: 'Monatsplan OP-Team',
  //         dienste: [
  //           56, 65, 63, 60, 70, 44, 32, 37, 39, 41, 42, 45, 48, 50, 52, 53, 61,
  //           68, 29, 31, 33, 34, 35, 36, 43, 49, 51, 62, 58, 59, 72, 66, 69, 57,
  //           71, 67, 30, 38, 40, 47, 54, 55, 64,
  //         ],
  //         created_at: '2022-03-24T17:43:08.329+01:00',
  //         updated_at: '2024-11-13T15:34:56.568+01:00',
  //         team_id: 4,
  //         funktionen_ids: [2, 3, 4],
  //         ansicht_id: 0,
  //         position: 1,
  //         allgemeine_vorlage: {
  //           id: 8,
  //           vorlage_id: 6,
  //           dienstplan_path_id: 14,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(OP-Team)_(Datum-Dienste)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [],
  //           freitext: '',
  //           publish: ['Datum-Dienste'],
  //         },
  //       },
  //       {
  //         id: 31,
  //         mitarbeiter_id: 12,
  //         name: 'E99/AWR',
  //         dienste: [
  //           183, 176, 179, 180, 182, 184, 181, 190, 91, 150, 145, 146, 147, 148,
  //           149, 151, 152, 153, 141, 169, 90, 93, 69, 85, 86, 95, 114, 89, 99,
  //           88, 97, 87, 115, 92,
  //         ],
  //         created_at: '2024-05-08T11:24:28.171+02:00',
  //         updated_at: '2024-11-13T15:29:42.157+01:00',
  //         team_id: 1,
  //         funktionen_ids: [3, 4, 5],
  //         ansicht_id: 1,
  //         position: 2,
  //         allgemeine_vorlage: {
  //           id: 7,
  //           vorlage_id: 31,
  //           dienstplan_path_id: 3,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(E99-AWR)_(Mitarbeiter-Datum)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [],
  //           freitext: '',
  //           publish: ['Mitarbeiter-Datum'],
  //         },
  //       },
  //       {
  //         id: 23,
  //         mitarbeiter_id: 576,
  //         name: 'Kopf Intensiv',
  //         dienste: [
  //           203, 183, 185, 179, 180, 182, 181, 190, 76, 91, 160, 161, 162, 158,
  //           159, 141, 90, 93, 85, 86, 95, 114, 89, 99, 88, 97, 87, 115, 92,
  //         ],
  //         created_at: '2022-10-11T15:03:10.529+02:00',
  //         updated_at: '2024-11-13T15:33:00.839+01:00',
  //         team_id: 2,
  //         funktionen_ids: [1, 2, 3, 4],
  //         ansicht_id: 1,
  //         position: 3,
  //         allgemeine_vorlage: {
  //           id: 1,
  //           vorlage_id: 23,
  //           dienstplan_path_id: 1,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(Kopf-Intensiv)_(Mitarbeiter-Datum)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [134, 135, 138, 168, 170],
  //           freitext: '',
  //           publish: ['Mitarbeiter-Datum'],
  //         },
  //       },
  //       {
  //         id: 24,
  //         mitarbeiter_id: 576,
  //         name: 'Ortho Intensiv',
  //         dienste: [
  //           183, 186, 179, 180, 182, 181, 190, 91, 141, 90, 93, 85, 86, 95, 114,
  //           89, 155, 156, 157, 99, 154, 88, 97, 87, 115, 92,
  //         ],
  //         created_at: '2023-01-10T10:19:54.744+01:00',
  //         updated_at: '2024-11-13T15:33:15.163+01:00',
  //         team_id: 3,
  //         funktionen_ids: [1, 2, 3, 4, 10],
  //         ansicht_id: 1,
  //         position: 4,
  //         allgemeine_vorlage: {
  //           id: 2,
  //           vorlage_id: 24,
  //           dienstplan_path_id: 2,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(Ortho-Intensiv)_(Mitarbeiter-Datum)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [136, 134, 135, 175],
  //           freitext: '',
  //           publish: ['Mitarbeiter-Datum'],
  //         },
  //       },
  //       {
  //         id: 7,
  //         mitarbeiter_id: 12,
  //         name: 'OA Dienstplan',
  //         dienste: [137, 136, 134, 139, 135, 138],
  //         created_at: '2022-03-24T17:48:08.746+01:00',
  //         updated_at: '2024-11-13T15:33:34.571+01:00',
  //         team_id: 6,
  //         funktionen_ids: [1, 2],
  //         ansicht_id: 0,
  //         position: 5,
  //         allgemeine_vorlage: {
  //           id: 6,
  //           vorlage_id: 7,
  //           dienstplan_path_id: 4,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(Ober-rzte-1)_(Datum-Dienste)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [],
  //           freitext: '',
  //           publish: ['Datum-Dienste'],
  //         },
  //       },
  //       {
  //         id: 30,
  //         mitarbeiter_id: 24,
  //         name: 'Ortho Org-Plan',
  //         dienste: [133, 136, 175, 174, 60, 61, 62],
  //         created_at: '2023-12-15T10:13:21.430+01:00',
  //         updated_at: '2024-11-13T15:33:47.759+01:00',
  //         team_id: 6,
  //         funktionen_ids: [1, 2, 3],
  //         ansicht_id: 0,
  //         position: 6,
  //         allgemeine_vorlage: {
  //           id: 5,
  //           vorlage_id: 30,
  //           dienstplan_path_id: 2,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(Ober-rzte)_(Datum-Dienste)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [174, 62],
  //           freitext: '',
  //           publish: ['Datum-Dienste'],
  //         },
  //       },
  //       {
  //         id: 25,
  //         mitarbeiter_id: 12,
  //         name: 'Urlaubsplan',
  //         dienste: [
  //           111, 188, 107, 108, 104, 163, 142, 45, 105, 93, 109, 112, 85, 86,
  //           113, 110, 95, 94, 99, 117, 88, 97, 96, 116, 87, 115, 98, 92,
  //         ],
  //         created_at: '2023-01-25T14:30:36.834+01:00',
  //         updated_at: '2024-11-13T15:33:58.480+01:00',
  //         team_id: null,
  //         funktionen_ids: [1, 2, 3, 4, 8, 7, 6, 5],
  //         ansicht_id: 1,
  //         position: 10,
  //         allgemeine_vorlage: {
  //           id: 3,
  //           vorlage_id: 25,
  //           dienstplan_path_id: 3,
  //           publishable: true,
  //           filepattern:
  //             '^DPL_(Kein-Team)_(Mitarbeiter-Datum)_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [],
  //           freitext: '',
  //           publish: ['Mitarbeiter-Datum'],
  //         },
  //       },
  //       {
  //         id: 29,
  //         mitarbeiter_id: 12,
  //         name: 'OP Frühdienste',
  //         dienste: [
  //           133, 128, 120, 121, 177, 124, 129, 122, 84, 131, 77, 181, 119, 193,
  //           78, 80, 118, 130, 123, 76, 74, 127, 126, 75, 132, 125, 140, 81, 79,
  //           141, 82, 83,
  //         ],
  //         created_at: '2023-10-13T13:52:20.734+02:00',
  //         updated_at: '2024-11-13T15:34:07.959+01:00',
  //         team_id: 4,
  //         funktionen_ids: [1, 2, 3, 4],
  //         ansicht_id: 0,
  //         position: 11,
  //         allgemeine_vorlage: {
  //           id: 4,
  //           vorlage_id: 29,
  //           dienstplan_path_id: 1,
  //           publishable: false,
  //           filepattern:
  //             '^DPL_(OP-Team)_()_([0-9]{4})-(0[1-9]|1[0-2])_v([0-9]+).pdf$',
  //           order: 0,
  //           pdf_zusatz_dienste: [],
  //           freitext: '',
  //           publish: [],
  //         },
  //       },
  //     ],
  //     dienstplan_custom_felder: [
  //       {
  //         id: 14,
  //         ansicht_id: 1,
  //         vorlage_id: 6,
  //         row: false,
  //         index: 1,
  //         name: 'AZ',
  //         count_all_typ: 2,
  //         created_at: '2022-09-12T12:58:50.121Z',
  //         updated_at: '2022-09-12T13:05:15.738Z',
  //         custom_counter_ids: [16],
  //       },
  //       {
  //         id: 18,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: true,
  //         index: 1,
  //         name: 'Früh-/Tag',
  //         count_all_typ: 5,
  //         created_at: '2022-10-11T13:31:26.749Z',
  //         updated_at: '2024-10-07T19:13:07.795Z',
  //         custom_counter_ids: [22],
  //       },
  //       {
  //         id: 17,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: false,
  //         index: 1,
  //         name: 'SOLL',
  //         count_all_typ: 1,
  //         created_at: '2022-10-11T13:04:17.178Z',
  //         updated_at: '2024-09-12T09:41:05.785Z',
  //         custom_counter_ids: [56],
  //       },
  //       {
  //         id: 51,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: true,
  //         index: 2,
  //         name: 'Zwischen',
  //         count_all_typ: 0,
  //         created_at: '2024-10-07T19:16:55.246Z',
  //         updated_at: '2024-10-07T19:19:25.656Z',
  //         custom_counter_ids: [91],
  //       },
  //       {
  //         id: 38,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: false,
  //         index: 2,
  //         name: 'IST',
  //         count_all_typ: 0,
  //         created_at: '2024-09-12T09:41:20.744Z',
  //         updated_at: '2024-09-12T09:41:57.964Z',
  //         custom_counter_ids: [77],
  //       },
  //       {
  //         id: 39,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: false,
  //         index: 3,
  //         name: 'Saldo',
  //         count_all_typ: 0,
  //         created_at: '2024-09-12T09:41:27.593Z',
  //         updated_at: '2024-09-12T09:42:40.251Z',
  //         custom_counter_ids: [78],
  //       },
  //       {
  //         id: 52,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: true,
  //         index: 3,
  //         name: 'Spät',
  //         count_all_typ: 0,
  //         created_at: '2024-10-07T19:22:27.256Z',
  //         updated_at: '2024-10-07T19:23:16.778Z',
  //         custom_counter_ids: [92],
  //       },
  //       {
  //         id: 53,
  //         ansicht_id: 1,
  //         vorlage_id: 23,
  //         row: true,
  //         index: 4,
  //         name: 'Nacht',
  //         count_all_typ: 0,
  //         created_at: '2024-10-07T19:22:34.605Z',
  //         updated_at: '2024-10-07T19:26:16.501Z',
  //         custom_counter_ids: [93],
  //       },
  //       {
  //         id: 21,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: false,
  //         index: 1,
  //         name: 'SOLL',
  //         count_all_typ: 0,
  //         created_at: '2023-01-12T10:31:05.526Z',
  //         updated_at: '2024-09-11T13:06:11.831Z',
  //         custom_counter_ids: [57],
  //       },
  //       {
  //         id: 24,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: true,
  //         index: 1,
  //         name: 'Tag',
  //         count_all_typ: 0,
  //         created_at: '2023-01-12T10:59:58.672Z',
  //         updated_at: '2024-10-07T19:42:28.370Z',
  //         custom_counter_ids: [38],
  //       },
  //       {
  //         id: 36,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: false,
  //         index: 2,
  //         name: 'IST',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T13:07:01.653Z',
  //         updated_at: '2024-09-11T13:07:49.871Z',
  //         custom_counter_ids: [75],
  //       },
  //       {
  //         id: 54,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: true,
  //         index: 2,
  //         name: 'Zwischen',
  //         count_all_typ: 0,
  //         created_at: '2024-10-07T19:42:04.810Z',
  //         updated_at: '2024-10-07T19:43:38.787Z',
  //         custom_counter_ids: [94],
  //       },
  //       {
  //         id: 55,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: true,
  //         index: 3,
  //         name: 'Nacht',
  //         count_all_typ: 0,
  //         created_at: '2024-10-07T19:42:15.239Z',
  //         updated_at: '2024-10-07T19:45:58.900Z',
  //         custom_counter_ids: [95],
  //       },
  //       {
  //         id: 37,
  //         ansicht_id: 1,
  //         vorlage_id: 24,
  //         row: false,
  //         index: 3,
  //         name: 'Saldo',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T13:07:08.835Z',
  //         updated_at: '2024-09-11T13:08:50.566Z',
  //         custom_counter_ids: [76],
  //       },
  //       {
  //         id: 31,
  //         ansicht_id: 1,
  //         vorlage_id: 25,
  //         row: false,
  //         index: 1,
  //         name: 'test',
  //         count_all_typ: 0,
  //         created_at: '2023-05-26T13:00:28.830Z',
  //         updated_at: '2023-05-26T13:00:46.396Z',
  //         custom_counter_ids: [52, 53],
  //       },
  //       {
  //         id: 29,
  //         ansicht_id: 1,
  //         vorlage_id: 25,
  //         row: true,
  //         index: 1,
  //         name: 'Zähler',
  //         count_all_typ: 0,
  //         created_at: '2023-02-05T09:42:34.057Z',
  //         updated_at: '2023-02-05T09:43:20.037Z',
  //         custom_counter_ids: [50],
  //       },
  //       {
  //         id: 33,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: false,
  //         index: 1,
  //         name: 'SOLL',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T09:08:08.264Z',
  //         updated_at: '2024-10-11T10:31:02.904Z',
  //         custom_counter_ids: [70, 100],
  //       },
  //       {
  //         id: 32,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 1,
  //         name: 'T E99',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T05:30:46.169Z',
  //         updated_at: '2024-09-13T08:28:47.748Z',
  //         custom_counter_ids: [79],
  //       },
  //       {
  //         id: 34,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: false,
  //         index: 2,
  //         name: 'SALDO',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T09:43:32.852Z',
  //         updated_at: '2024-10-11T10:32:53.519Z',
  //         custom_counter_ids: [101],
  //       },
  //       {
  //         id: 40,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 2,
  //         name: 'T AWR',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:28:33.132Z',
  //         updated_at: '2024-09-13T08:32:40.261Z',
  //         custom_counter_ids: [80],
  //       },
  //       {
  //         id: 35,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: false,
  //         index: 3,
  //         name: 'T',
  //         count_all_typ: 0,
  //         created_at: '2024-09-11T09:43:41.504Z',
  //         updated_at: '2024-10-11T10:35:55.205Z',
  //         custom_counter_ids: [102, 103],
  //       },
  //       {
  //         id: 41,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 3,
  //         name: 'F E99',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:29:10.042Z',
  //         updated_at: '2024-09-13T08:33:14.400Z',
  //         custom_counter_ids: [81],
  //       },
  //       {
  //         id: 42,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 4,
  //         name: 'N E99',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:29:19.961Z',
  //         updated_at: '2024-09-13T08:38:44.126Z',
  //         custom_counter_ids: [82],
  //       },
  //       {
  //         id: 56,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: false,
  //         index: 4,
  //         name: 'N',
  //         count_all_typ: 0,
  //         created_at: '2024-10-11T10:18:54.724Z',
  //         updated_at: '2024-10-11T10:27:19.153Z',
  //         custom_counter_ids: [96, 97],
  //       },
  //       {
  //         id: 43,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 5,
  //         name: 'N AWR',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:29:28.664Z',
  //         updated_at: '2024-09-13T08:39:50.029Z',
  //         custom_counter_ids: [83],
  //       },
  //       {
  //         id: 44,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 6,
  //         name: 'Schmerz',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:29:45.665Z',
  //         updated_at: '2024-09-13T08:45:40.891Z',
  //         custom_counter_ids: [84],
  //       },
  //       {
  //         id: 45,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 7,
  //         name: 'S AWR',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:29:54.728Z',
  //         updated_at: '2024-09-13T08:46:58.750Z',
  //         custom_counter_ids: [85],
  //       },
  //       {
  //         id: 46,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 8,
  //         name: 'Z E99',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:30:08.525Z',
  //         updated_at: '2024-09-13T08:48:10.992Z',
  //         custom_counter_ids: [86],
  //       },
  //       {
  //         id: 47,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 9,
  //         name: 'AD',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:30:52.043Z',
  //         updated_at: '2024-09-13T08:48:56.392Z',
  //         custom_counter_ids: [87],
  //       },
  //       {
  //         id: 48,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 10,
  //         name: 'NEF',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:30:58.994Z',
  //         updated_at: '2024-09-13T08:49:42.133Z',
  //         custom_counter_ids: [88],
  //       },
  //       {
  //         id: 49,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 11,
  //         name: 'NEF Hosp',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:31:12.319Z',
  //         updated_at: '2024-09-13T08:51:05.520Z',
  //         custom_counter_ids: [89],
  //       },
  //       {
  //         id: 50,
  //         ansicht_id: 1,
  //         vorlage_id: 31,
  //         row: true,
  //         index: 12,
  //         name: 'RTH',
  //         count_all_typ: 0,
  //         created_at: '2024-09-13T08:31:28.788Z',
  //         updated_at: '2024-09-13T09:02:17.060Z',
  //         custom_counter_ids: [90],
  //       },
  //     ],
  //     dienstplan_custom_counter: [
  //       {
  //         id: 16,
  //         name: 'AZ',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 14,
  //         beschreibung: '',
  //         cell_id: 'headcell_0_0_0_0_0_1',
  //         created_at: '2022-09-12T12:59:27.224Z',
  //         updated_at: '2022-09-12T13:06:29.246Z',
  //         date_ids: [
  //           '1t1',
  //           '2t1',
  //           '3t1',
  //           '4t1',
  //           '5t1',
  //           '6t1',
  //           '7t1',
  //           '8t1',
  //           '9t1',
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //           '-8t-1',
  //           '-7t-1',
  //           '-6t-1',
  //           '-5t-1',
  //           '-4t-1',
  //           '-3t-1',
  //           '-2t-1',
  //           '-1t-1',
  //           '0t-1',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: true,
  //         count: 'Arbeitszeiten (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 56,
  //         name: 'SOLL',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 17,
  //         beschreibung: 'SOLL Stunden/Monat',
  //         cell_id: '466_0__0',
  //         created_at: '2024-07-18T13:12:29.012Z',
  //         updated_at: '2024-07-18T13:12:29.012Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Soll Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 22,
  //         name: 'Frühdienste/Tagdienste',
  //         dienste_ids: [162, 158],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 18,
  //         beschreibung: 'Frühdienste/Tagdienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2022-10-11T13:34:05.723Z',
  //         updated_at: '2024-10-07T19:16:16.805Z',
  //         date_ids: [
  //           '-8t-1',
  //           '-7t-1',
  //           '-6t-1',
  //           '-5t-1',
  //           '-4t-1',
  //           '-3t-1',
  //           '-2t-1',
  //           '-1t-1',
  //           '0t-1',
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //           '1t1',
  //           '2t1',
  //           '3t1',
  //           '4t1',
  //           '5t1',
  //           '6t1',
  //           '7t1',
  //           '8t1',
  //           '9t1',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#2b9c2d',
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [2],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 57,
  //         name: 'SOLL',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 21,
  //         beschreibung: 'Sollstunden pro Monat',
  //         cell_id: '572_0__0',
  //         created_at: '2024-07-18T13:19:37.726Z',
  //         updated_at: '2024-07-18T13:19:37.726Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Soll Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 38,
  //         name: 'Tag',
  //         dienste_ids: [156],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 24,
  //         beschreibung: 'Tagdienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2023-01-12T11:02:52.007Z',
  //         updated_at: '2024-10-07T21:03:52.735Z',
  //         date_ids: [
  //           '-8t-1',
  //           '-7t-1',
  //           '-6t-1',
  //           '-5t-1',
  //           '-4t-1',
  //           '-3t-1',
  //           '-2t-1',
  //           '-1t-1',
  //           '0t-1',
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //           '1t1',
  //           '2t1',
  //           '3t1',
  //           '4t1',
  //           '5t1',
  //           '6t1',
  //           '7t1',
  //           '8t1',
  //           '9t1',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_2_SPLIT_#2bff7e',
  //           'Ergebnis_SPLIT_>_SPLIT_2_SPLIT_#2b9c2d',
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#dcff5c',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [3],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 50,
  //         name: 'Urlaubsstatistik',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 29,
  //         beschreibung: 'Urlaubsstatistik',
  //         cell_id: 'headdate_1_11_2t0_0_0_false',
  //         created_at: '2023-02-05T09:43:20.025Z',
  //         updated_at: '2023-02-05T09:52:18.889Z',
  //         date_ids: [],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Urlaubsstatistik',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 52,
  //         name: 'Neuer Zähler',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 31,
  //         beschreibung: 'Test Zähler',
  //         cell_id: 'bodycell_0_0_0_0_185_1',
  //         created_at: '2023-05-26T13:00:40.384Z',
  //         updated_at: '2023-05-26T13:00:40.384Z',
  //         date_ids: [],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 53,
  //         name: 'Neuer Zähler',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 31,
  //         beschreibung: 'Test Zähler',
  //         cell_id: 'bodycell_0_0_0_0_185_1',
  //         created_at: '2023-05-26T13:00:46.390Z',
  //         updated_at: '2023-05-26T13:00:46.390Z',
  //         date_ids: [],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Arbeitszeiten (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 79,
  //         name: 'T E99',
  //         dienste_ids: [146],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 32,
  //         beschreibung: 'Tagdienst E99',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:25:31.088Z',
  //         updated_at: '2024-09-23T09:15:02.712Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f57070',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_2_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_2_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 70,
  //         name: 'Soll',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 33,
  //         beschreibung: 'Sollstunden',
  //         cell_id: '572_0__0',
  //         created_at: '2024-09-11T09:09:12.697Z',
  //         updated_at: '2024-09-11T09:26:25.366Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: false,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Soll Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 100,
  //         name: 'IST',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 33,
  //         beschreibung: 'IST Stunden',
  //         cell_id: '370_0__0',
  //         created_at: '2024-10-11T10:31:02.886Z',
  //         updated_at: '2024-10-11T10:31:02.886Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Ist Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 101,
  //         name: 'Saldo',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 34,
  //         beschreibung: 'Saldo',
  //         cell_id: '0_0__0',
  //         created_at: '2024-10-11T10:32:53.497Z',
  //         updated_at: '2024-10-11T10:32:53.497Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Arbeitszeit Saldo (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 102,
  //         name: 'T E99',
  //         dienste_ids: [146],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 35,
  //         beschreibung: 'Anzahl Tagdienste E99',
  //         cell_id: '0_0__0',
  //         created_at: '2024-10-11T10:34:34.063Z',
  //         updated_at: '2024-10-11T10:34:34.063Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 103,
  //         name: 'T AWR',
  //         dienste_ids: [149],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 35,
  //         beschreibung: 'Anzahl Tagdienste AWR',
  //         cell_id: '0_0__0',
  //         created_at: '2024-10-11T10:35:16.083Z',
  //         updated_at: '2024-10-11T10:35:16.083Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 75,
  //         name: 'IST',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 36,
  //         beschreibung: 'IST Stunden',
  //         cell_id: '0_0__0',
  //         created_at: '2024-09-11T13:07:49.854Z',
  //         updated_at: '2024-09-11T13:07:49.854Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Ist Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 76,
  //         name: 'Saldo',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 37,
  //         beschreibung: 'Saldo IST-SOLL',
  //         cell_id: '0_0__0',
  //         created_at: '2024-09-11T13:08:50.558Z',
  //         updated_at: '2024-09-11T13:08:50.558Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Arbeitszeit Saldo (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 77,
  //         name: 'Neuer Zähler',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 38,
  //         beschreibung: 'Test Zähler',
  //         cell_id: '466_0__0',
  //         created_at: '2024-09-12T09:41:57.946Z',
  //         updated_at: '2024-09-12T09:41:57.946Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Ist Arbeitszeit (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 78,
  //         name: 'Neuer Zähler',
  //         dienste_ids: [],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 39,
  //         beschreibung: 'Test Zähler',
  //         cell_id: '547_0__0',
  //         created_at: '2024-09-12T09:42:40.235Z',
  //         updated_at: '2024-09-12T09:42:40.235Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Arbeitszeit Saldo (Std)',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 80,
  //         name: 'T AWR',
  //         dienste_ids: [149],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 40,
  //         beschreibung: 'Tagdienst AWR',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:32:40.239Z',
  //         updated_at: '2024-09-23T09:18:26.033Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f57070',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 81,
  //         name: 'F E99',
  //         dienste_ids: [145],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 41,
  //         beschreibung: 'Frühdienst E99',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:33:14.383Z',
  //         updated_at: '2024-09-23T09:20:10.573Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_>=_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 82,
  //         name: 'N E99',
  //         dienste_ids: [147],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 42,
  //         beschreibung: 'Nachtdienst E99',
  //         cell_id: '0_0_2t0_0',
  //         created_at: '2024-09-13T08:38:44.108Z',
  //         updated_at: '2024-09-23T09:21:53.311Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<=_SPLIT_0.0_SPLIT_#f57070',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_2_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_2_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 83,
  //         name: 'N AWR',
  //         dienste_ids: [150],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 43,
  //         beschreibung: 'Nachtdienst AWR',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:39:50.012Z',
  //         updated_at: '2024-09-23T09:22:47.077Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<=_SPLIT_0.0_SPLIT_#f57070',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_0.0_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 84,
  //         name: 'S E99',
  //         dienste_ids: [148],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 44,
  //         beschreibung: 'Schmerzdienst',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:45:40.874Z',
  //         updated_at: '2024-09-23T09:23:50.681Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 85,
  //         name: 'S AWR',
  //         dienste_ids: [152],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 45,
  //         beschreibung: 'Spätdienst AWR',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:46:58.740Z',
  //         updated_at: '2024-09-23T09:25:31.356Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 86,
  //         name: 'Z E99',
  //         dienste_ids: [151],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 46,
  //         beschreibung: 'Zwischendienst E99',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:48:10.975Z',
  //         updated_at: '2024-09-23T09:26:47.456Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 87,
  //         name: 'AD',
  //         dienste_ids: [176],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 47,
  //         beschreibung: 'Angiodienst',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:48:56.375Z',
  //         updated_at: '2024-09-23T09:27:44.774Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#ccffff',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 88,
  //         name: 'NEFs',
  //         dienste_ids: [70, 67, 66, 71, 68, 69],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 48,
  //         beschreibung: 'Notarztdienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:49:42.116Z',
  //         updated_at: '2024-09-23T09:29:07.197Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<=_SPLIT_0.0_SPLIT_#f99543',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#8ac2ff',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#f99543',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [1],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 89,
  //         name: 'NEF Hosp',
  //         dienste_ids: [198, 197, 199, 195, 196],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 49,
  //         beschreibung: 'NEF Hospitationen',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T08:51:05.496Z',
  //         updated_at: '2024-09-23T09:30:26.624Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: ['Ergebnis_SPLIT_>=_SPLIT_1_SPLIT_#ccffff'],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [1],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 90,
  //         name: 'RTH',
  //         dienste_ids: [72],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 50,
  //         beschreibung: 'RTH C53',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-09-13T09:01:52.951Z',
  //         updated_at: '2024-09-23T09:30:10.502Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: ['Ergebnis_SPLIT_>=_SPLIT_1_SPLIT_#ccffff'],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [1],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 91,
  //         name: 'Zwischen',
  //         dienste_ids: [159],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 51,
  //         beschreibung: 'Zwischendienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-10-07T19:19:25.635Z',
  //         updated_at: '2024-10-07T19:19:25.635Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#2b9c2d',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 92,
  //         name: 'Spät',
  //         dienste_ids: [160],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 52,
  //         beschreibung: 'Spätdienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-10-07T19:23:16.762Z',
  //         updated_at: '2024-10-07T19:25:00.905Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#2b9c2d',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 93,
  //         name: 'Nacht',
  //         dienste_ids: [203, 161],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 53,
  //         beschreibung: 'Nachtdienste',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-10-07T19:26:16.483Z',
  //         updated_at: '2024-10-07T19:27:24.516Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#2b9c2d',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 94,
  //         name: 'Zwischen',
  //         dienste_ids: [155],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 54,
  //         beschreibung: 'Zwischendienst',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-10-07T19:43:38.770Z',
  //         updated_at: '2024-10-07T19:44:55.147Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_1_SPLIT_#2b9c2d',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 95,
  //         name: 'Nacht',
  //         dienste_ids: [157],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 55,
  //         beschreibung: 'Nachtdienst',
  //         cell_id: '0_0_1t0_0',
  //         created_at: '2024-10-07T19:45:58.884Z',
  //         updated_at: '2024-10-07T20:17:10.736Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: [
  //           'Ergebnis_SPLIT_<_SPLIT_1_SPLIT_#ffae00',
  //           'Ergebnis_SPLIT_=_SPLIT_1_SPLIT_#2bff00',
  //           'Ergebnis_SPLIT_>_SPLIT_0.0_SPLIT_#2b9c2d',
  //         ],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 96,
  //         name: 'N E99',
  //         dienste_ids: [147],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 56,
  //         beschreibung: 'Anzahl Nachtdienste',
  //         cell_id: '370_0__0',
  //         created_at: '2024-10-11T10:20:21.831Z',
  //         updated_at: '2024-10-17T12:36:24.615Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: ['Ergebnis_SPLIT_>_SPLIT_4_SPLIT_#f99543'],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //       {
  //         id: 97,
  //         name: 'NA',
  //         dienste_ids: [150],
  //         mitarbeiter_ids: [],
  //         dienstplan_custom_feld_id: 56,
  //         beschreibung: 'Anzahl Nachtdienste AWR',
  //         cell_id: '370_0__0',
  //         created_at: '2024-10-11T10:25:45.665Z',
  //         updated_at: '2024-10-17T12:36:48.545Z',
  //         date_ids: [
  //           '1t0',
  //           '2t0',
  //           '3t0',
  //           '4t0',
  //           '5t0',
  //           '6t0',
  //           '7t0',
  //           '8t0',
  //           '9t0',
  //           '10t0',
  //           '11t0',
  //           '12t0',
  //           '13t0',
  //           '14t0',
  //           '15t0',
  //           '16t0',
  //           '17t0',
  //           '18t0',
  //           '19t0',
  //           '20t0',
  //           '21t0',
  //           '22t0',
  //           '23t0',
  //           '24t0',
  //           '25t0',
  //           '26t0',
  //           '27t0',
  //           '28t0',
  //           '29t0',
  //           '30t0',
  //           '31t0',
  //         ],
  //         colors: ['Ergebnis_SPLIT_>_SPLIT_4_SPLIT_#f99543'],
  //         hidden: false,
  //         aktiv: true,
  //         inaktiv: true,
  //         currently_in_team: true,
  //         mit_bedarf: true,
  //         ohne_bedarf: true,
  //         act_as_funktion: false,
  //         evaluate_seperate: true,
  //         add_kein_mitarbeiterteam: false,
  //         count: 'Einteilungen',
  //         funktion: '',
  //         feiertage: 'auch',
  //         mitarbeiterteam_ids: [],
  //         mitarbeiterfunktionen_ids: [],
  //         diensteteam_ids: [],
  //         wochentage: [0, 1, 2, 3, 4, 5, 6],
  //         empty_as_regeldienst: false,
  //       },
  //     ],
  //     dienstplaner_settings: {
  //       user_settings: null,
  //       farbgruppen: [],
  //     },
  //   },
  //   monatsplan_ansichten: [
  //     'Datum-Dienste',
  //     'Mitarbeiter-Datum',
  //     'Mitarbeiter-Dienste',
  //   ],
  //   ratings: result.dienstratings,
  //   vertragstyp_varianten: { 1: [1] },
  //   publicvorlagen: {},
  // };
}

export { getAllApiData };
