import './global.css';
import '../styles/variables.css';

export const metadata = {
  title: 'Welcome to hains',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
